### ISSUE TITLE
programming header P1

### ISSUE THREAD

**Issue by VojislavM** [pointhi/HighPower-Mechaduino#13]
On the programming header P1 the pin 7 is connected to the ground, and in the Arduino zero [schematic](https://www.arduino.cc/en/uploads/Main/ArduinoZero-schematic.pdf) it is not. I know this is not a big deal, but maybe (in some parallel universe) it could bother the programator when connected.

**Comment by pointhi** [comment]
@VojislavM , thanks for spotting this

Just for documentation (from atmel website):

![](http://www.atmel.com/webdoc/atmelice/images/sam_swd_header.png)
