### ISSUE TITLE
pcb mounting holes

### ISSUE THREAD

**Issue by feichtinger** [pointhi/HighPower-Mechaduino#15]
I started to design a housing/mounting for the HighPower-Mechaduino on a NEMA24 stepper motor and discovered that the mounting holes in the PCB are made for M4 only while they are for M5 in the motor. See this screenshot:
![bildschirmfoto vom 2017-01-03 22-25-57](https://cloud.githubusercontent.com/assets/10723283/21624706/62b6f2ae-d208-11e6-8603-f6baabc41cf7.png)

(The CAD model is based on measurements form an actual motor.)

See also this datasheet of a NEMA 23 motor:
http://www.omc-stepperonline.com/download/pdf/23HS16-0884S.pdf

I think it would be good to change mounting holes in the pcb to fit to M5 screws (a diameter of 5.2mm should be sufficient)

There might be some NEMA23/24 motors where the mounting holes are actually M4, but it is easier to fit an M4 screw into an M5 hole than the other way round. ;)

**Comment by pointhi** [comment]
fixed: fba158e134bf2179033e19b4fcdc3ea2f984c09f
