### ISSUE TITLE
Shunt Resistors

### ISSUE THREAD

**Issue by feichtinger** [pointhi/HighPower-Mechaduino#4]
I think a resistor with 4-wire-connection should be used for the shunt resistors R16 and R19. Otherwise the load current flowing throw the groundplane could lead to a wrong current feedback due to the parasitic resistance and inductance.

The connection on the drain side is already (almost) correct, but not so on the ground plane.

**Comment by pointhi** [comment]
unfortunately, our motor controller doesn't support such types of shunts. Probably we could arrange the tracks a bit to minify voltage drops as much as possible.
